"""initial_competency_and_role_architecture

Revision ID: 838740a90065
Revises: 
Create Date: 2026-08-26 19:18:11.378773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '838740a90065'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('user_competencies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('target_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_assessed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_competencies_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_competencies_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_competencies_user_id'), ['user_id'], unique=False)

    op.create_table('ai_diagnoses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('primary_gap', sa.String(length=255), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_diagnoses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_diagnoses_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_diagnoses_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_diagnoses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_diagnoses_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('competency_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resource_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('match_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.alter_column('content',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_ai_recommendations_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'courses', ['resource_id'], ['id'])
        batch_op.create_foreign_key(None, 'competencies', ['competency_id'], ['id'])

    with op.batch_alter_table('assessment_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('response_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('answered_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessment_answers_assessment_id'), ['assessment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_answers_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_type', sa.String(length=50), nullable=False))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_assessments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_competencies_name'), ['name'], unique=True)

    with op.batch_alter_table('competency_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competency_dependencies_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competency_dependencies_prerequisite_id'), ['prerequisite_id'], unique=False)

    with op.batch_alter_table('competency_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competency_scores_assessed_at'), ['assessed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_competency_scores_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competency_scores_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('course_competencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_competencies_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_competencies_course_id'), ['course_id'], unique=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('external_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('competency_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_courses_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_topic_id'), ['topic_id'], unique=False)
        batch_op.create_foreign_key(None, 'competencies', ['competency_id'], ['id'])
        batch_op.create_foreign_key(None, 'competency_topics', ['topic_id'], ['id'])

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('generated_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_questions_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_questions_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('competency_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_learning_materials_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_materials_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_foreign_key(None, 'competencies', ['competency_id'], ['id'])

    with op.batch_alter_table('learning_path_items', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_learning_path_items_learning_path_id'), ['learning_path_id'], unique=False)

    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_paths_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progress_percentage', sa.Float(), nullable=True))
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_learning_progress_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_question_options_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('question_text', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('options_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('source_material_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_ai_generated', sa.Boolean(), nullable=True))
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('explanation',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_questions_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_topic_id'), ['topic_id'], unique=False)
        batch_op.create_foreign_key(None, 'learning_materials', ['source_material_id'], ['id'])
        batch_op.create_foreign_key(None, 'competency_topics', ['topic_id'], ['id'])
        batch_op.drop_column('question_type')

    with op.batch_alter_table('role_competencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('target_score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('target_level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_role_competencies_competency_id'), ['competency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_competencies_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_competencies_role_name'), ['role_name'], unique=False)
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])
        batch_op.drop_column('required_level')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_department_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('department_name')
        batch_op.drop_column('role_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('role_competencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_level', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_role_competencies_role_name'))
        batch_op.drop_index(batch_op.f('ix_role_competencies_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_competencies_competency_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('weight')
        batch_op.drop_column('target_level')
        batch_op.drop_column('target_score')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_questions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_questions_competency_id'))
        batch_op.alter_column('explanation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_ai_generated')
        batch_op.drop_column('source_material_id')
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('options_json')
        batch_op.drop_column('question_text')
        batch_op.drop_column('topic_id')

    with op.batch_alter_table('question_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_options_question_id'))
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('learning_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_course_id'))
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('progress_percentage')
        batch_op.drop_column('resource_id')

    with op.batch_alter_table('learning_paths', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_paths_user_id'))

    with op.batch_alter_table('learning_path_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_path_items_learning_path_id'))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('learning_materials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_learning_materials_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_learning_materials_competency_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('competency_id')
        batch_op.drop_column('storage_path')

    with op.batch_alter_table('generated_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_questions_question_id'))
        batch_op.drop_index(batch_op.f('ix_generated_questions_material_id'))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_courses_topic_id'))
        batch_op.drop_index(batch_op.f('ix_courses_competency_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('topic_id')
        batch_op.drop_column('competency_id')
        batch_op.drop_column('url')
        batch_op.drop_column('external_id')
        batch_op.drop_column('resource_type')

    with op.batch_alter_table('course_competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_competencies_course_id'))
        batch_op.drop_index(batch_op.f('ix_course_competencies_competency_id'))

    with op.batch_alter_table('competency_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competency_scores_user_id'))
        batch_op.drop_index(batch_op.f('ix_competency_scores_competency_id'))
        batch_op.drop_index(batch_op.f('ix_competency_scores_assessed_at'))

    with op.batch_alter_table('competency_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competency_dependencies_prerequisite_id'))
        batch_op.drop_index(batch_op.f('ix_competency_dependencies_competency_id'))

    with op.batch_alter_table('competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competencies_name'))
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('category')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_user_id'))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('assessment_type')

    with op.batch_alter_table('assessment_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_answers_assessment_id'))
        batch_op.drop_column('answered_at')
        batch_op.drop_column('response_time')
        batch_op.drop_column('selected_answer')

    with op.batch_alter_table('ai_recommendations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ai_recommendations_user_id'))
        batch_op.alter_column('content',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('reason')
        batch_op.drop_column('match_score')
        batch_op.drop_column('resource_id')
        batch_op.drop_column('competency_id')

    with op.batch_alter_table('ai_diagnoses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_diagnoses_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_diagnoses_id'))
        batch_op.drop_index(batch_op.f('ix_ai_diagnoses_competency_id'))
        batch_op.drop_index(batch_op.f('ix_ai_diagnoses_assessment_id'))

    op.drop_table('ai_diagnoses')
    with op.batch_alter_table('user_competencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_competencies_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_competencies_id'))
        batch_op.drop_index(batch_op.f('ix_user_competencies_competency_id'))

    op.drop_table('user_competencies')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    # ### end Alembic commands ###
