import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { questionApi, competencyApi } from '@/lib/api';
import { 
  Search, Eye, Check, X, RefreshCw, Sparkles, Database, Plus, 
  Layers, CheckCircle2, AlertCircle, Edit3, Filter, HelpCircle, BookOpen, Clock
} from 'lucide-react';
import { cn } from '@/lib/utils';

export default function QuestionBank() {
  const [questions, setQuestions] = useState<any[]>([]);
  const [competencies, setCompetencies] = useState<any[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [search, setSearch] = useState<string>('');
  const [statusFilter, setStatusFilter] = useState<string>('all');
  const [selectedComp, setSelectedComp] = useState<string>('all');
  const [selectedDiff, setSelectedDiff] = useState<string>('all');
  
  // Modals / Inspections
  const [inspectingQ, setInspectingQ] = useState<any | null>(null);
  const [editingQ, setEditingQ] = useState<any | null>(null);
  const [showGenModal, setShowGenModal] = useState<boolean>(false);
  
  // Generation Form State
  const [genCompId, setGenCompId] = useState<string>('1');
  const [genTopicName, setGenTopicName] = useState<string>('Stratified Sampling');
  const [genDiff, setGenDiff] = useState<string>('2');
  const [genCount, setGenCount] = useState<number>(5);
  const [generating, setGenerating] = useState<boolean>(false);
  const [actionSuccess, setActionSuccess] = useState<string | null>(null);

  const fetchQuestions = async () => {
    try {
      setLoading(true);
      const [qRes, cRes] = await Promise.allSettled([
        questionApi.getAll({
          status: statusFilter !== 'all' ? statusFilter : undefined,
          competency_id: selectedComp !== 'all' ? parseInt(selectedComp) : undefined,
          difficulty: selectedDiff !== 'all' ? selectedDiff : undefined,
          search: search || undefined
        }),
        competencyApi.getAll()
      ]);

      if (qRes.status === 'fulfilled') {
        setQuestions(qRes.value.data || []);
      }
      if (cRes.status === 'fulfilled') {
        setCompetencies(cRes.value.data || []);
      }
    } catch (err) {
      console.error('Failed to load questions:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchQuestions();
  }, [statusFilter, selectedComp, selectedDiff]);

  const handleSearchSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    fetchQuestions();
  };

  const handleStatusChange = async (questionId: number, newStatus: 'approved' | 'rejected' | 'pending_review') => {
    try {
      await questionApi.updateStatus(questionId, newStatus);
      setActionSuccess(`Question #${questionId} marked as ${newStatus}.`);
      setTimeout(() => setActionSuccess(null), 3000);
      setQuestions(prev => prev.map(q => q.id === questionId ? { ...q, status: newStatus } : q));
      if (inspectingQ?.id === questionId) {
        setInspectingQ({ ...inspectingQ, status: newStatus });
      }
    } catch (err) {
      console.error('Failed to update question status:', err);
    }
  };

  const handleRegenerate = async (questionId: number) => {
    try {
      setLoading(true);
      const res = await questionApi.regenerate(questionId);
      setActionSuccess(`Question #${questionId} regenerated by AIService.`);
      setTimeout(() => setActionSuccess(null), 3000);
      fetchQuestions();
    } catch (err) {
      console.error('Failed to regenerate question:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateSet = async () => {
    try {
      setGenerating(true);
      const res = await questionApi.generate({
        competency_id: parseInt(genCompId),
        topic_id: undefined,
        difficulty: genDiff,
        count: genCount
      });
      setShowGenModal(false);
      setActionSuccess(`Synthesized ${res.data?.generated_count || genCount} candidate questions. Ready for review.`);
      setTimeout(() => setActionSuccess(null), 4000);
      setStatusFilter('pending_review');
      fetchQuestions();
    } catch (err) {
      console.error('Generation set failed:', err);
    } finally {
      setGenerating(false);
    }
  };

  const handleSaveEdit = async () => {
    if (!editingQ) return;
    try {
      await questionApi.update(editingQ.id, {
        text: editingQ.question_text || editingQ.text,
        explanation: editingQ.explanation,
        difficulty: editingQ.difficulty,
        source_reference: editingQ.source_reference,
        options: editingQ.options
      });
      setActionSuccess(`Question #${editingQ.id} changes saved.`);
      setTimeout(() => setActionSuccess(null), 3000);
      setEditingQ(null);
      fetchQuestions();
    } catch (err) {
      console.error('Failed to save question edit:', err);
    }
  };

  return (
    <div className="space-y-8 max-w-7xl mx-auto pb-16 text-left">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <div className="flex items-center space-x-2 text-xs font-mono font-bold text-[#176B87] uppercase tracking-widest mb-1">
            <Database className="w-3.5 h-3.5" />
            <span>AI CURATION & REVIEW ENGINE</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-[#123047] tracking-tight">
            Official Question Bank
          </h1>
          <p className="text-xs sm:text-sm text-[#5D7180] mt-1">
            Review, calibrate, and approve source-grounded questions. Only approved questions enter the active adaptive assessment pool.
          </p>
        </div>
        
        <Button 
          onClick={() => setShowGenModal(true)}
          className="bg-[#176B87] hover:bg-[#176B87]/90 text-[#FFFFFF] font-semibold text-xs sm:text-sm shadow-xs cursor-pointer h-10 px-4 rounded-xl"
        >
          <Sparkles className="w-4 h-4 mr-1.5 text-[#D49A2A]" />
          <span>Generate Question Set</span>
        </Button>
      </div>

      {/* Action Notification */}
      {actionSuccess && (
        <div className="p-3.5 rounded-xl bg-[#2E8B57]/10 border border-[#2E8B57]/30 text-xs font-bold font-mono text-[#2E8B57] flex items-center gap-2 animate-in fade-in duration-200">
          <CheckCircle2 className="w-4 h-4" />
          <span>{actionSuccess}</span>
        </div>
      )}

      {/* Filter and Search Bar */}
      <div className="grid grid-cols-1 sm:grid-cols-12 gap-3 p-4 bg-[#FFFFFF] rounded-2xl shadow-[0_1px_3px_rgba(11,37,69,0.04)] border border-[#D8E5EC]">
        <div className="sm:col-span-5 relative">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#5D7180]/60 w-4 h-4" />
          <form onSubmit={handleSearchSubmit}>
            <Input 
              placeholder="Search by question text or keyword..." 
              className="pl-10 border-[#D8E5EC] focus:border-[#176B87] text-xs h-10 bg-[#FFFFFF] rounded-xl text-[#123047]" 
              value={search} 
              onChange={(e) => setSearch(e.target.value)} 
            />
          </form>
        </div>

        <div className="sm:col-span-3">
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="border-[#D8E5EC] bg-[#FFFFFF] text-xs h-10 rounded-xl">
              <SelectValue placeholder="All Statuses" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Statuses</SelectItem>
              <SelectItem value="pending_review">Pending Review</SelectItem>
              <SelectItem value="approved">Approved (Active Pool)</SelectItem>
              <SelectItem value="rejected">Rejected</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="sm:col-span-2">
          <Select value={selectedComp} onValueChange={setSelectedComp}>
            <SelectTrigger className="border-[#D8E5EC] bg-[#FFFFFF] text-xs h-10 rounded-xl">
              <SelectValue placeholder="All Competencies" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Competencies</SelectItem>
              {competencies.map(c => (
                <SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <div className="sm:col-span-2">
          <Select value={selectedDiff} onValueChange={setSelectedDiff}>
            <SelectTrigger className="border-[#D8E5EC] bg-[#FFFFFF] text-xs h-10 rounded-xl">
              <SelectValue placeholder="All Difficulties" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Difficulties</SelectItem>
              <SelectItem value="1">1 - Foundational (Easy)</SelectItem>
              <SelectItem value="2">2 - Intermediate (Medium)</SelectItem>
              <SelectItem value="3">3 - Advanced (Hard)</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Main Questions Table */}
      <Card className="bg-[#FFFFFF] shadow-[0_1px_3px_rgba(11,37,69,0.04)] border border-[#D8E5EC] rounded-2xl overflow-hidden">
        <CardHeader className="bg-[#EAF3F7] border-b border-[#D8E5EC] p-5 pb-3">
          <div className="flex justify-between items-center">
            <CardTitle className="text-xs font-mono font-bold text-[#123047] uppercase tracking-wider flex items-center gap-2">
              <Layers className="w-4 h-4 text-[#176B87]" />
              Repository Questions ({questions.length})
            </CardTitle>
            <span className="text-[11px] font-mono text-[#5D7180]">
              Approved items are eligible for adaptive test sessions
            </span>
          </div>
        </CardHeader>

        <CardContent className="p-0">
          {loading ? (
            <div className="p-8 text-center text-xs text-[#5D7180] font-semibold">Loading questions...</div>
          ) : questions.length === 0 ? (
            <div className="p-8 text-center text-xs text-[#5D7180]">
              No questions found matching criteria. Click <strong>Generate Question Set</strong> to create questions using AI.
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left text-xs">
                <thead className="bg-[#EAF3F7] border-b border-[#D8E5EC] text-[#123047] uppercase tracking-wider font-semibold font-mono text-[10px]">
                  <tr>
                    <th className="px-5 py-3.5 w-2/5">Question Text & Citation</th>
                    <th className="px-5 py-3.5">Competency</th>
                    <th className="px-5 py-3.5">Difficulty</th>
                    <th className="px-5 py-3.5">Status</th>
                    <th className="px-5 py-3.5 text-right">Review Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#D8E5EC] font-medium text-[#123047]">
                  {questions.map(q => {
                    const isApproved = q.status === 'approved';
                    const isRejected = q.status === 'rejected';
                    const isPending = q.status === 'pending_review';

                    return (
                      <tr key={q.id} className="hover:bg-[#EAF3F7]/50 transition-colors">
                        <td className="px-5 py-3.5">
                          <p className="font-bold text-[#123047] line-clamp-2">{q.question_text || q.text}</p>
                          <span className="text-[10px] font-mono text-[#5D7180] block mt-0.5">
                            Source: {q.source_reference || 'MoSPI Official Handbook'}
                          </span>
                        </td>
                        <td className="px-5 py-3.5">
                          <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded-full bg-[#176B87]/10 text-[#176B87] border border-[#176B87]/20">
                            {q.competency_name}
                          </span>
                        </td>
                        <td className="px-5 py-3.5 font-mono">
                          <span className="text-xs">
                            {q.difficulty === '3' || q.difficulty === 'hard' || q.difficulty === 'advanced' ? 'Hard (3)' :
                             q.difficulty === '1' || q.difficulty === 'easy' || q.difficulty === 'foundational' ? 'Easy (1)' : 'Medium (2)'}
                          </span>
                        </td>
                        <td className="px-5 py-3.5">
                          <span className={cn(
                            "px-2 py-0.5 rounded-full text-[10px] font-mono font-bold border uppercase",
                            isApproved 
                              ? "bg-[#2E8B57]/10 text-[#2E8B57] border-[#2E8B57]/30"
                              : isRejected
                              ? "bg-[#D49A2A]/15 text-[#123B5D] border-[#D49A2A]/35"
                              : "bg-[#176B87]/10 text-[#176B87] border-[#176B87]/20"
                          )}>
                            {isApproved ? 'Approved' : isRejected ? 'Rejected' : 'Pending Review'}
                          </span>
                        </td>
                        <td className="px-5 py-3.5 text-right space-x-1">
                          <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => setInspectingQ(q)}
                            className="h-7 px-2 text-[#176B87] hover:bg-[#176B87]/10 text-[11px] font-bold cursor-pointer" 
                            title="Inspect Question"
                          >
                            <Eye className="w-3.5 h-3.5 mr-1" /> Inspect
                          </Button>
                          
                          {!isApproved && (
                            <Button 
                              variant="ghost" 
                              size="sm" 
                              onClick={() => handleStatusChange(q.id, 'approved')}
                              className="h-7 px-2 text-[#2E8B57] hover:bg-[#2E8B57]/10 text-[11px] font-bold cursor-pointer" 
                              title="Approve Question"
                            >
                              <Check className="w-3.5 h-3.5 mr-1" /> Approve
                            </Button>
                          )}

                          {!isRejected && (
                            <Button 
                              variant="ghost" 
                              size="sm" 
                              onClick={() => handleStatusChange(q.id, 'rejected')}
                              className="h-7 px-2 text-[#D49A2A] hover:bg-[#D49A2A]/15 text-[11px] font-bold cursor-pointer" 
                              title="Reject Question"
                            >
                              <X className="w-3.5 h-3.5 mr-1" /> Reject
                            </Button>
                          )}

                          <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => setEditingQ(JSON.parse(JSON.stringify(q)))}
                            className="h-7 px-2 text-[#123047]/70 hover:text-[#123B5D] text-[11px] font-bold cursor-pointer" 
                            title="Edit Question"
                          >
                            <Edit3 className="w-3.5 h-3.5" />
                          </Button>

                          <Button 
                            variant="ghost" 
                            size="sm" 
                            onClick={() => handleRegenerate(q.id)}
                            className="h-7 px-2 text-[#123047]/60 hover:text-[#176B87] text-[11px] cursor-pointer" 
                            title="AI Regenerate"
                          >
                            <RefreshCw className="w-3.5 h-3.5" />
                          </Button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* ============================================================ */}
      {/* MODAL 1: INSPECT QUESTION DETAILS                             */}
      {/* ============================================================ */}
      {inspectingQ && (
        <div className="fixed inset-0 bg-[#123B5D]/40 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-in fade-in duration-200">
          <div className="bg-[#FFFFFF] max-w-2xl w-full rounded-2xl p-6 border border-[#D8E5EC] shadow-xl space-y-5 text-left max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-[#D8E5EC] pb-3">
              <div className="space-y-0.5">
                <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-[#176B87]">
                  {inspectingQ.competency_name} // QUESTION #{inspectingQ.id}
                </span>
                <h3 className="text-base font-bold text-[#123047]">Source-Grounded MCQ Inspection</h3>
              </div>
              <Button variant="ghost" size="icon" onClick={() => setInspectingQ(null)} className="h-8 w-8 text-[#5D7180] hover:text-[#123047] rounded-lg">
                <X className="w-4 h-4" />
              </Button>
            </div>

            <div className="space-y-4 text-xs">
              <div>
                <span className="text-[10px] font-mono font-bold text-[#5D7180] uppercase block mb-1">Question Prompt</span>
                <p className="p-3.5 rounded-xl bg-[#EAF3F7] border border-[#D8E5EC] font-bold text-sm text-[#123047]">
                  {inspectingQ.question_text || inspectingQ.text}
                </p>
              </div>

              <div>
                <span className="text-[10px] font-mono font-bold text-[#5D7180] uppercase block mb-1.5">Options</span>
                <div className="space-y-2">
                  {inspectingQ.options?.map((opt: any, idx: number) => {
                    const isCorrect = opt.is_correct || opt.option_text === inspectingQ.correct_answer;
                    return (
                      <div 
                        key={idx}
                        className={cn(
                          "p-3 rounded-xl border flex items-center justify-between",
                          isCorrect 
                            ? "bg-[#2E8B57]/10 border-[#2E8B57]/40 text-[#2E8B57] font-bold" 
                            : "bg-[#FFFFFF] border-[#D8E5EC] text-[#123047]"
                        )}
                      >
                        <span>{opt.option_text || opt.text}</span>
                        {isCorrect && (
                          <span className="text-[10px] font-mono font-bold px-2 py-0.5 bg-[#2E8B57] text-[#FFFFFF] rounded-md">
                            Correct Answer
                          </span>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>

              <div className="p-3.5 rounded-xl bg-[#EAF3F7] border border-[#D8E5EC] space-y-1">
                <span className="text-[10px] font-mono font-bold text-[#176B87] uppercase block">Explanation</span>
                <p className="text-[#123047] leading-relaxed">{inspectingQ.explanation}</p>
              </div>

              <div className="grid grid-cols-2 gap-2 text-[11px] font-mono">
                <div className="p-2.5 rounded-xl bg-[#EAF3F7] border border-[#D8E5EC]">
                  <span className="text-[#5D7180] block text-[9px]">Source Citation:</span>
                  <span className="font-bold text-[#123047]">{inspectingQ.source_reference || 'MoSPI Standard'}</span>
                </div>
                <div className="p-2.5 rounded-xl bg-[#EAF3F7] border border-[#D8E5EC]">
                  <span className="text-[#5D7180] block text-[9px]">Cognitive Target:</span>
                  <span className="font-bold text-[#123047] uppercase">{inspectingQ.cognitive_level || 'Apply'}</span>
                </div>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-2 border-t border-[#D8E5EC]">
              <Button 
                variant="outline" 
                size="sm" 
                onClick={() => {
                  handleStatusChange(inspectingQ.id, 'rejected');
                  setInspectingQ(null);
                }} 
                className="text-[#D49A2A] border-[#D49A2A]/40 text-xs font-semibold rounded-xl h-8.5"
              >
                Reject Question
              </Button>
              <Button 
                size="sm" 
                onClick={() => {
                  handleStatusChange(inspectingQ.id, 'approved');
                  setInspectingQ(null);
                }} 
                className="bg-[#2E8B57] hover:bg-[#2E8B57]/90 text-[#FFFFFF] text-xs font-semibold rounded-xl h-8.5"
              >
                Approve & Add to Pool
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* ============================================================ */}
      {/* MODAL 2: GENERATE NEW CANDIDATE QUESTION SET                 */}
      {/* ============================================================ */}
      {showGenModal && (
        <div className="fixed inset-0 bg-[#123B5D]/40 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-in fade-in duration-200">
          <div className="bg-[#FFFFFF] max-w-lg w-full rounded-2xl p-6 border border-[#D8E5EC] shadow-xl space-y-5 text-left">
            <div className="flex items-center justify-between border-b border-[#D8E5EC] pb-3">
              <div className="space-y-0.5">
                <span className="text-[10px] font-mono font-bold uppercase tracking-wider text-[#176B87]">
                  ON-DEMAND AI SYNTHESIS
                </span>
                <h3 className="text-base font-bold text-[#123047]">Generate Question Set</h3>
              </div>
              <Button variant="ghost" size="icon" onClick={() => setShowGenModal(false)} className="h-8 w-8 text-[#5D7180] hover:text-[#123047] rounded-lg">
                <X className="w-4 h-4" />
              </Button>
            </div>

            <div className="space-y-4 text-xs">
              <div>
                <label className="text-[11px] font-bold text-[#123047] block mb-1">Competency Area</label>
                <Select value={genCompId} onValueChange={setGenCompId}>
                  <SelectTrigger className="border-[#D8E5EC] bg-[#FFFFFF] text-xs h-10 rounded-xl">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {competencies.map(c => (
                      <SelectItem key={c.id} value={String(c.id)}>{c.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div>
                <label className="text-[11px] font-bold text-[#123047] block mb-1">Subtopic Focus</label>
                <Input 
                  value={genTopicName}
                  onChange={(e) => setGenTopicName(e.target.value)}
                  placeholder="e.g. Neyman Optimal Allocation, Variance Estimation"
                  className="border-[#D8E5EC] text-xs h-10 rounded-xl"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-[11px] font-bold text-[#123047] block mb-1">Difficulty</label>
                  <Select value={genDiff} onValueChange={setGenDiff}>
                    <SelectTrigger className="border-[#D8E5EC] bg-[#FFFFFF] text-xs h-10 rounded-xl">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="1">1 - Foundational (Easy)</SelectItem>
                      <SelectItem value="2">2 - Intermediate (Medium)</SelectItem>
                      <SelectItem value="3">3 - Advanced (Hard)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <label className="text-[11px] font-bold text-[#123047] block mb-1">Question Count</label>
                  <Select value={String(genCount)} onValueChange={(val) => setGenCount(parseInt(val))}>
                    <SelectTrigger className="border-[#D8E5EC] bg-[#FFFFFF] text-xs h-10 rounded-xl">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="3">3 Questions</SelectItem>
                      <SelectItem value="5">5 Questions</SelectItem>
                      <SelectItem value="10">10 Questions</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <p className="text-[11px] text-[#5D7180] leading-relaxed font-mono bg-[#EAF3F7] p-3 rounded-xl border border-[#D8E5EC]">
                Generated questions will undergo schema validation (4 options, 1 correct answer) and appear in the <strong>Pending Review</strong> queue before entering the active pool.
              </p>
            </div>

            <div className="flex justify-end gap-2 pt-2 border-t border-[#D8E5EC]">
              <Button variant="outline" size="sm" onClick={() => setShowGenModal(false)} className="text-xs font-semibold rounded-xl h-8.5">
                Cancel
              </Button>
              <Button 
                size="sm" 
                onClick={handleGenerateSet}
                disabled={generating}
                className="bg-[#176B87] hover:bg-[#176B87]/90 text-[#FFFFFF] text-xs font-semibold rounded-xl h-8.5 cursor-pointer"
              >
                <Sparkles className={`w-3.5 h-3.5 mr-1.5 ${generating ? 'animate-spin' : ''}`} />
                <span>{generating ? 'Synthesizing with AI...' : 'Generate Questions'}</span>
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* ============================================================ */}
      {/* MODAL 3: EDIT QUESTION                                       */}
      {/* ============================================================ */}
      {editingQ && (
        <div className="fixed inset-0 bg-[#123B5D]/40 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-in fade-in duration-200">
          <div className="bg-[#FFFFFF] max-w-2xl w-full rounded-2xl p-6 border border-[#D8E5EC] shadow-xl space-y-4 text-left max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between border-b border-[#D8E5EC] pb-3">
              <h3 className="text-base font-bold text-[#123047]">Edit Question #{editingQ.id}</h3>
              <Button variant="ghost" size="icon" onClick={() => setEditingQ(null)} className="h-8 w-8 text-[#5D7180] hover:text-[#123047] rounded-lg">
                <X className="w-4 h-4" />
              </Button>
            </div>

            <div className="space-y-3 text-xs">
              <div>
                <label className="font-bold text-[#123047] block mb-1">Question Prompt</label>
                <textarea 
                  value={editingQ.question_text || editingQ.text}
                  onChange={(e) => setEditingQ({ ...editingQ, text: e.target.value, question_text: e.target.value })}
                  className="w-full p-2.5 rounded-xl border border-[#D8E5EC] text-xs font-medium focus:border-[#176B87] focus:outline-none"
                  rows={3}
                />
              </div>

              <div>
                <label className="font-bold text-[#123047] block mb-1">Explanation</label>
                <textarea 
                  value={editingQ.explanation || ''}
                  onChange={(e) => setEditingQ({ ...editingQ, explanation: e.target.value })}
                  className="w-full p-2.5 rounded-xl border border-[#D8E5EC] text-xs font-medium focus:border-[#176B87] focus:outline-none"
                  rows={2}
                />
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-2 border-t border-[#D8E5EC]">
              <Button variant="outline" size="sm" onClick={() => setEditingQ(null)} className="text-xs font-semibold rounded-xl h-8.5">
                Cancel
              </Button>
              <Button size="sm" onClick={handleSaveEdit} className="bg-[#176B87] hover:bg-[#176B87]/90 text-[#FFFFFF] text-xs font-semibold rounded-xl h-8.5">
                Save Changes
              </Button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
